# Generated by Django 6.0.7 on 2026-07-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('nama_lapak', models.CharField(default='Martabak Pak Joko', max_length=100)),
                ('goqris_apikey', models.CharField(blank=True, default='', max_length=255)),
                ('goqris_project_name', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
                'db_table': 'settings',
            },
        ),
    ]
