# Generated by Django 5.2.16 on 2026-07-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='nama_lapak',
        ),
    ]
