# Generated by Django 5.2.16 on 2026-07-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_remove_settings_nama_lapak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='goqris_apikey',
        ),
    ]
