# Generated by Django 6.0.7 on 2026-07-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.BigIntegerField(help_text='Harga dalam rupiah')),
                ('category', models.CharField(choices=[('manis', 'Manis'), ('telur', 'Telur'), ('tipis', 'Tipis')], max_length=50)),
                ('emoji', models.CharField(default='🥞', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
                'db_table': 'menus',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
