# Generated by Django 5.2.16 on 2026-07-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, help_text='Gambar menu (optional)', null=True, upload_to='menus/'),
        ),
    ]
