# Generated by Django 5.2.16 on 2026-07-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['category', 'sort_order', 'name'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('category', 'sort_order'), name='unique_sort_order_per_category'),
        ),
    ]
