# Generated by Django 5.2.16 on 2026-07-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('goqris', 'GoQris QRIS'), ('cash', 'Tunai')], default='goqris', help_text='Metode pembayaran: goqris (QRIS) atau cash (Tunai)', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_label',
            field=models.CharField(blank=True, default='', help_text='Label metode pembayaran untuk display (e.g. "GoQris QRIS", "Tunai")', max_length=50),
        ),
    ]
