# Generated by Django 5.2.16 on 2026-07-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_payment_method_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qr_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
