# Generated by Django 5.2.16 on 2026-07-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_menu_options_and_more'),
        ('orders', '0003_fix_qr_image_url_textfield'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'menu'), name='unique_menu_per_order'),
        ),
    ]
