# Generated by Django 5.2.16 on 2026-07-30 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama bahan baku (bebas)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material Item',
                'verbose_name_plural': 'Material Items',
                'db_table': 'material_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCostEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(help_text='Tanggal mulai periode')),
                ('date_to', models.DateField(help_text='Tanggal akhir periode')),
                ('total_cost', models.IntegerField(default=0, help_text='Total biaya bahan baku (calculated from items)')),
                ('total_revenue', models.IntegerField(default=0, help_text='Total pendapatan dari orders (calculated)')),
                ('profit', models.IntegerField(default=0, help_text='Laba = total_revenue - total_cost')),
                ('notes', models.TextField(blank=True, help_text='Catatan opsional', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Cost Entry',
                'verbose_name_plural': 'Material Cost Entries',
                'db_table': 'material_cost_entries',
                'ordering': ['-date_from'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(help_text='Nama bahan (free text)', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Jumlah bahan', max_digits=10)),
                ('price_per_unit', models.IntegerField(help_text='Harga per unit')),
                ('subtotal', models.IntegerField(default=0, help_text='quantity × price_per_unit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='raw_materials.materialcostentry')),
            ],
            options={
                'verbose_name': 'Material Cost Item',
                'verbose_name_plural': 'Material Cost Items',
                'db_table': 'material_cost_items',
            },
        ),
    ]
