# Generated by Django 5.2.16 on 2026-07-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcostentry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
