# Generated by Django 6.0.7 on 2026-07-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0002_add_is_active_to_cost_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcostitem',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='Satuan (contoh: kg, gram, butir, liter, pcs, zak, dll)', max_length=20),
        ),
    ]
